### ISSUE TITLE
Scoreboard. Invalid Eff value

### ISSUE THREAD

**Issue by et-nik** [tmp64/BugfixedHL#12]
It is not clear how it is calculated **Eff value**

I think **Eff = Kills / Deaths**

If so Eff value should be 1.00 instead of 0.95. Because my Score is 8, and Deaths is 8.
![20200107133045_1](https://user-images.githubusercontent.com/3670640/71969196-39962800-3217-11ea-949f-7981b810ccad.jpg)

![20200107135846_1](https://user-images.githubusercontent.com/3670640/71969355-8c6fdf80-3217-11ea-85fb-4b06f7453a28.jpg)

**Comment by tmp64** [comment]
There are two efficiency formulas:

1. **Kills / Deaths** -- *hud_scoreboard_efftype 0*;
2. **Kills / (Deaths + 1)** or **Kills / Lives** -- *hud_scoreboard_efftype 1*, which is default.

That is why it's called "efficiency" and not simply "K/D".

Initially, the default formula was used to not divide by zero. Later, someone asked to add the other one.
