### ISSUE TITLE
Customizable crosshairs mixed with original sometimes

### ISSUE THREAD

**Issue by et-nik** [tmp64/BugfixedHL#13]
Version: build-141, ["[client] Fix MOTD close delay" commit](https://github.com/tmp64/BugfixedHL/commit/88fd92f8948a16ac5739716e08821322c6b9d920)
OS: Windows 10

Always mixed on crossbow aiming (Right click)

![20200109151652_1](https://user-images.githubusercontent.com/3670640/72139918-8d804880-33a0-11ea-8fb5-1065d5181b3a.jpg)

Sometimes mixed on gauss and egon.
![20200109192528_1](https://user-images.githubusercontent.com/3670640/72139987-c0c2d780-33a0-11ea-8674-8dc61fc6ac3f.jpg)
![20200109193355_1](https://user-images.githubusercontent.com/3670640/72139988-c0c2d780-33a0-11ea-8f96-fb818eabf2e6.jpg)

**Comment by tmp64** [comment]
1) Sprite crosshair is always shown when zoomed-in on crossbow or WeaponMod weapons.
2) Fixed.
