### ISSUE TITLE
Can i run this modification in re-hlds?

### ISSUE THREAD

**Issue by XMILKAY** [tmp64/BugfixedHL#17]
Hello Tmp64. 
Thanks for this modification. 
I used it in default steam half-life and this modification worked without any problems. But when I try to play with re-hlds, I get an error. I am sending this error in the attachment.
![Screenshot_15](https://user-images.githubusercontent.com/63732211/81898584-9fc5f980-95c1-11ea-94ab-ae02a00e9f73.png) 

I would be very happy if you help me.

**Comment by tmp64** [comment]
Hi. This error message is generated by the client. You say you installed ReHLDS so I guess you installed it on the client (correct me if I'm wrong). While this is not recommended, it shouldn't cause any problems. Please attach *crash.log* and *crash.dmp* so I can debug it.

**Comment by XMILKAY** [comment]
I can connect to servers and i play without problems. But i can't create server. 
[crash.zip](https://github.com/tmp64/BugfixedHL/files/4626453/crash.zip)

**Comment by tmp64** [comment]
I installed latest ReHLDS on latest Steam client, installed v1.4.0 client (with VGUI2) and server and couldn't reproduce the crash. Please provide version of everything you have installed (game, ReHLDS, Metamod, AMXX, etc).

However, I recommend installing HLDS from SteamCMD and use it for ReHLDS.

**Comment by XMILKAY** [comment]
I found the source of the problem. When I start with Metamod (r) .dll it crashes. I think I am making errors in re-hlds and metamod-r setup.
