### ISSUE TITLE
Scoreboard VGUI2. Show who i was killed by.

### ISSUE THREAD

**Issue by antnmntla** [tmp64/BugfixedHL#18]
Hello, tmp64.
Can you enable option to show who i was killed by in VGUI2 scoreboard (red line like in vgui1)? Or can i use old scoreboard in VGUI2 build?

**Comment by tmp64** [comment]
That is something I totally forgot about. I'll add it on the weekend.

You can try to `bind tab +showoldscores` but I can't guarantee it will work correctly.

**Comment by antnmntla** [comment]
Thank you. I will use +showoldscores for now.
