### ISSUE TITLE
Incorrect speed detection on moving platforms

### ISSUE THREAD

**Issue by Safety1st** [tmp64/BugfixedHL#19]
![image](https://user-images.githubusercontent.com/1483401/89127965-adbd5380-d4fa-11ea-94db-0bf7d82e9dfc.png)
![image](https://user-images.githubusercontent.com/1483401/89127966-b2820780-d4fa-11ea-8efc-5fe485b0550d.png)

**Comment by tmp64** [comment]
Actual speed of the player is calculated by the engine based on player's own speed (shown in the speedometer) and platform speed. You can notice that by jumping while standing on a moving platform: once you jump, you'll lose the platform speed.

The real velocity is not exposed to the client DLL AFAIK.
