### ISSUE TITLE
Кракозябры вместо UTF-8 символов в имени игрока для спектатора

### ISSUE THREAD

**Issue by Safety1st** [tmp64/BugfixedHL#20]
В данном примере `сс` набрано кириллицей:
![image](https://user-images.githubusercontent.com/1483401/89227571-98bdee80-d5e6-11ea-8efa-90ac4b27cb61.png)

Ещё пример, тут у игрока несколько другой ник:
![image](https://user-images.githubusercontent.com/1483401/89227730-df134d80-d5e6-11ea-91c8-23cef198e9bc.png)

**Comment by tmp64** [comment]
Для Spectator UI используется VGUI1, который Юникод не поддерживает. Я переделал его на VGUI2, но пока что не зарелизил.
