### ISSUE TITLE
Suggestion: add second option to block self-gauss completely

### ISSUE THREAD

**Issue by Safety1st** [tmp64/BugfixedHL#23]
For now with `mp_selfgauss 0` there is no reverse beam damage, but… Sometimes there is normal deflection from other surfaces. Look at the picture below and/or the [video](https://youtu.be/BNvyEumK9Ok) to reproduce the issue. It could be undesired for those who use AMXX plugins like [Anti Self-Gauss](http://aghl.ru/forum/viewtopic.php?f=19&t=19). **We are fine with current behaviour** but others might want 'legacy' blocking :wink:

![image](https://user-images.githubusercontent.com/1483401/89836900-6e34de00-db70-11ea-8c58-2b336cc0427a.png)
![image](https://user-images.githubusercontent.com/1483401/89836911-71c86500-db70-11ea-8ac5-5db2b3c99445.png)

**Comment by tmp64** [comment]
9d51dcc added `mp_selfgauss 2` that will block all selfgauss damage.
