### ISSUE TITLE
Cvar Chat - Enabled / Disabled Sound

### ISSUE THREAD

**Issue by DJMayroN** [tmp64/BugfixedHL#24]
Add Cvar - enable / disable sound in the Chat of sent messages

Please Dmitry, do it.

**Comment by tmp64** [comment]
Thanks for the suggestion. I added `hud_saytext_sound` cvar in cd6fd3e that enables or disables chat sound (enabled by default).

**Comment by DJMayroN** [comment]
Thank.
However, I didn't see it in the console cvar lists.
Did you add it recently or just now?

Maybe you forgot to add 4554 for build? (i use it)

**Comment by tmp64** [comment]
I added it today so it is only available in the latest [development build](https://ci.appveyor.com/project/tmp64/bugfixedhl/branch/master).

**Comment by DJMayroN** [comment]
I understood you
Thank you Dmitry
