### ISSUE TITLE
Timer (hud_timer 1) not moving when hud_timer_sync is enabled in LISTEN server

### ISSUE THREAD

**Issue by ddagger1** [tmp64/BugfixedHL#26]
![crossfire-01092020-204922](https://user-images.githubusercontent.com/70611792/91916884-b12c3200-ec94-11ea-9d8d-13c3ff88f699.jpg)

Using hud_timer_sync 1 causes this bug in LISTEN server only.

**Comment by tmp64** [comment]
Fixed, thanks

**Comment by ddagger1** [comment]
No problem dude, great job!
