### ISSUE TITLE
VGUI2 scoreboard marks non-spectators as non spectators

### ISSUE THREAD

**Issue by tmp64** [tmp64/BugfixedHL#4]

**Comment by tmp64** [comment]
@abdobiskra

> > It would be nice if you said how to reproduce the spectator bug in issue #4
>
>I am not good at explaining .. xD
But I am using the server system rounds (i used natives like hl_user_spawn() & hl_get_user_spectator() ... set_user_team() .. etc )
I leave you a demo to help you understand?
[debug_demo.zip](https://github.com/tmp64/BugfixedHL/files/2538661/debug_demo.zip)
or here ip of server : 173.249.21.128:27018

**Comment by tmp64** [comment]
@abdobiskra
It's a bug in hl.inc. It doesn't reset player's spectator flag.
Here's the fix:
```diff
*************** stock hl_set_user_spectator(client, bool
*** 396,401 ****
--- 396,411 ----

                set_pdata_int(client, OFFSET_HUD, 0)

+               // Send Spectator message (it is not used in vanila client dll)
+               static MsgSpectator
+               if(MsgSpectator || (MsgSpectator = get_user_msgid("Spectator")))
+               {
+                       message_begin(MSG_ALL, MsgSpectator)
+                       write_byte(client)
+                       write_byte(0)
+                       message_end()
+               }
+
                static szTeam[16]
                hl_get_user_team(client, szTeam, charsmax(szTeam))
```

Full stock:
```pawn
/* Switch player to spectator mode.
 */
stock hl_set_user_spectator(client, bool:spectator = true)
{
	if(hl_get_user_spectator(client) == spectator)
		return
	
	if(spectator)
	{
		static AllowSpectatorsCvar
		if(AllowSpectatorsCvar || (AllowSpectatorsCvar = get_cvar_pointer("allow_spectators")))
		{
			if(!get_pcvar_num(AllowSpectatorsCvar))
				set_pcvar_num(AllowSpectatorsCvar, 1)
			
			engclient_cmd(client, "spectate")
		}
	}
	else
	{
		hl_user_spawn(client)
			
		set_pev(client, pev_iuser1, 0)
		set_pev(client, pev_iuser2, 0)
			
		set_pdata_int(client, OFFSET_HUD, 0)
			
		// Send Spectator message (it is not used in vanila client dll)
		static MsgSpectator
		if(MsgSpectator || (MsgSpectator = get_user_msgid("Spectator")))
		{
			message_begin(MSG_ALL, MsgSpectator)
			write_byte(client)
			write_byte(0)
			message_end()
		}
			
		static szTeam[16]
		hl_get_user_team(client, szTeam, charsmax(szTeam))
		
		static TeamInfo
		if(TeamInfo || (TeamInfo = get_user_msgid("TeamInfo")))
		{
			message_begin(MSG_ALL, TeamInfo)
			write_byte(client)
			write_string(szTeam)
			message_end()
		}
	}
}
```

**Comment by abdobiskra** [comment]
But that does not happen with Lev release?

**Comment by tmp64** [comment]
Yes, it does. The old scoreboard is still available if you bind +showoldscore to any key (e.g. `bind alt +showoldscores`). Sorry for a bad photo, Steam doesn't allow to screenshot with ALT pressed.

![image](https://user-images.githubusercontent.com/20199236/47918416-22ef9500-dedf-11e8-939f-0b3a30112daa.png)

As you can see, everyone is marked as spectators although they are not. The VGUI2 scoreboard puts spectators in a separate team regardless of what team the belong to the server says.

I might add a convar to not group specatators unless the server does that itself and only mark them with "(spectator)".

**Comment by abdobiskra** [comment]
Maybe that is in the old version
But do not happen to me in the latest version
![20181102174633_1](https://user-images.githubusercontent.com/31223391/47928894-caf96400-dec7-11e8-99b4-091138526b08.jpg)

**Comment by tmp64** [comment]
There is a bug that causes the client to read Steam ID incorrectly. It is parsed from `status` command. Unfortunately, I don't know how to fix it because that part of the code looks more like magic than code.
